/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsPostRouteImport } from './routes/products/post'
import { Route as ProductsIdRouteImport } from './routes/products/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPostRoute = ProductsPostRouteImport.update({
  id: '/products/post',
  path: '/products/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/post': typeof ProductsPostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/post': typeof ProductsPostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/post': typeof ProductsPostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/products/$id' | '/products/post'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products/$id' | '/products/post'
  id: '__root__' | '/' | '/products/$id' | '/products/post'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsPostRoute: typeof ProductsPostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/post': {
      id: '/products/post'
      path: '/products/post'
      fullPath: '/products/post'
      preLoaderRoute: typeof ProductsPostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/products/$id' {
  const createFileRoute: CreateFileRoute<
    '/products/$id',
    FileRoutesByPath['/products/$id']['parentRoute'],
    FileRoutesByPath['/products/$id']['id'],
    FileRoutesByPath['/products/$id']['path'],
    FileRoutesByPath['/products/$id']['fullPath']
  >
}
declare module './routes/products/post' {
  const createFileRoute: CreateFileRoute<
    '/products/post',
    FileRoutesByPath['/products/post']['parentRoute'],
    FileRoutesByPath['/products/post']['id'],
    FileRoutesByPath['/products/post']['path'],
    FileRoutesByPath['/products/post']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsIdRoute: ProductsIdRoute,
  ProductsPostRoute: ProductsPostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
